### ISSUE TITLE
API키 입력시 액세스가 안됩니다. 

### ISSUE THREAD

**Issue by yunk0121** [FigmaAI/klever#1]

**Comment by dusskapark** [comment]
@yunk0121 혹시 아래의 주소로 들어갔을 때 충전한 금액이 보이는지 체크해봐주세요. 

https://platform.openai.com/settings/organization/billing/overview

오픈AI의 상품 구성이 좀 헷갈리게 되어 있어서 좀 더 체크가 필요할 것 같습니다
