### ISSUE TITLE
$5 달러 이상 충전완료 API를 넣었는데 submit이 안되네요

### ISSUE THREAD

**Issue by Kimmmj** [FigmaAI/klever#2]
<img width="566" alt="SCR-20240924-mzdx" src="https://github.com/user-attachments/assets/9d86dc95-941c-4c67-91c3-16bdcbcef7bd">
<img width="540" alt="SCR-20240924-mzya" src="https://github.com/user-attachments/assets/90ff0956-de57-482e-b700-96fd7b420c34">

**Comment by dusskapark** [comment]
플러그인을 리프레시 하는 부분에 버그가 있었네요. 감사합니다. 

버그 픽스 버전을 업데이트 했으니, 새로 배포된 버전을 사용해보시기 바랍니다.  (14번째 배포버전)
